//! One-time, non-destructive migration of pre-separation Brainstorm data.
//!
//! Before Brainstorm was extracted into this standalone app, the user's boards
//! lived in the DreamStore shell's pool (`~/DreamStore Projects/`). Standalone
//! Brainstorm uses its own isolated dirs (`~/Brainstorm Projects/` +
//! `~/.brainstorm/`) and does NOT share that pool. So on first launch we COPY
//! the existing Brainstorm boards across once, so the back-catalogue isn't
//! lost. After this one-time copy the two are fully independent — edits on one
//! side never touch the other.
//!
//! Properties:
//!   - **Non-destructive:** the shell's data is only read, never moved/deleted.
//!   - **Brainstorm-only:** only `~/DreamStore Projects/<dir>` folders
//!     containing a `board.json` are copied; kinetic/pulse/data/remit projects
//!     are skipped.
//!   - **Idempotent:** a marker at `~/.brainstorm/migrated.json` records that
//!     the copy ran, so it never repeats (even if the user later deletes every
//!     copied board).
//!   - **Only copies `board.json`:** the per-project `.claude/` skill symlink,
//!     `CLAUDE.md` and `.mcp.json` are regenerated by `project_open` / the
//!     canvas server, so we don't drag stale copies across.

use std::fs;
use std::path::Path;

const MARKER: &str = "migrated.json";

fn shell_projects_dir() -> Option<std::path::PathBuf> {
    dirs::home_dir().map(|h| h.join("DreamStore Projects"))
}

/// Run the one-time migration against the real dirs. Idempotent; best-effort
/// (a failure to copy any one item is logged to stderr, not fatal — the app
/// still launches).
pub fn migrate_once() {
    let Some(shell_projects) = shell_projects_dir() else {
        return;
    };
    migrate_in(
        &shell_projects,
        &crate::paths::projects_dir(),
        &crate::paths::user_dir(),
    );
}

/// Testable core: copy pre-separation Brainstorm boards from the shell pool
/// into the standalone dir, guarded by a one-shot marker under `bs_user`.
fn migrate_in(shell_projects: &Path, bs_projects: &Path, bs_user: &Path) {
    let marker = bs_user.join(MARKER);
    if marker.exists() {
        return; // already migrated
    }

    let mut copied_projects = 0usize;

    // Copy each shell Brainstorm project (a dir containing board.json).
    if shell_projects.is_dir() {
        if let Err(e) = fs::create_dir_all(bs_projects) {
            eprintln!("brainstorm migrate: mkdir pool: {}", e);
        }
        if let Ok(entries) = fs::read_dir(shell_projects) {
            for entry in entries.flatten() {
                let src = entry.path();
                if !src.is_dir() || !src.join("board.json").exists() {
                    continue;
                }
                let Some(name) = src.file_name() else { continue };
                let dst = bs_projects.join(name);
                if dst.exists() {
                    continue; // don't clobber an existing standalone project
                }
                if let Err(e) = fs::create_dir_all(&dst) {
                    eprintln!("brainstorm migrate: mkdir {}: {}", dst.display(), e);
                    continue;
                }
                // Only the doc; skill bundle + CLAUDE.md + .mcp.json are
                // regenerated on open.
                match fs::copy(src.join("board.json"), dst.join("board.json")) {
                    Ok(_) => copied_projects += 1,
                    Err(e) => eprintln!("brainstorm migrate: copy {}: {}", src.display(), e),
                }
            }
        }
    }

    // Drop the marker so this never runs again.
    if let Err(e) = fs::create_dir_all(bs_user) {
        eprintln!("brainstorm migrate: mkdir user dir for marker: {}", e);
        return;
    }
    let body = format!("{{\"copiedProjects\":{}}}\n", copied_projects);
    if let Err(e) = fs::write(&marker, body) {
        eprintln!("brainstorm migrate: write marker: {}", e);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Build a fake shell Brainstorm project dir with a board.json.
    fn board_project(pool: &Path, name: &str, body: &str) {
        let dir = pool.join(name);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("board.json"), body).unwrap();
    }

    #[test]
    fn copies_board_projects_once_and_skips_others() {
        let home = TempDir::new().unwrap();
        let shell_projects = home.path().join("DreamStore Projects");
        let bs_projects = home.path().join("Brainstorm Projects");
        let bs_user = home.path().join(".brainstorm");

        // Two boards + one kinetic project (story.json) that must be skipped.
        board_project(&shell_projects, "ideas", r#"{"type":"excalidraw"}"#);
        board_project(&shell_projects, "ideas-2", r#"{"type":"excalidraw"}"#);
        let kinetic = shell_projects.join("v1");
        fs::create_dir_all(&kinetic).unwrap();
        fs::write(kinetic.join("story.json"), "{}").unwrap();

        migrate_in(&shell_projects, &bs_projects, &bs_user);

        // Both boards copied (board.json only), kinetic skipped.
        assert!(bs_projects.join("ideas/board.json").exists());
        assert!(bs_projects.join("ideas-2/board.json").exists());
        assert!(!bs_projects.join("v1").exists(), "non-brainstorm project skipped");
        // Marker written.
        assert!(bs_user.join(MARKER).exists());
        // Shell data untouched (non-destructive).
        assert!(shell_projects.join("ideas/board.json").exists());
    }

    #[test]
    fn is_idempotent_and_does_not_reclobber() {
        let home = TempDir::new().unwrap();
        let shell_projects = home.path().join("DreamStore Projects");
        let bs_projects = home.path().join("Brainstorm Projects");
        let bs_user = home.path().join(".brainstorm");
        board_project(&shell_projects, "ideas", r#"{"type":"excalidraw"}"#);

        migrate_in(&shell_projects, &bs_projects, &bs_user);
        // User edits the copied board after migration.
        fs::write(bs_projects.join("ideas/board.json"), r#"{"edited":true}"#).unwrap();
        // Second run must NOT overwrite the user's edit (marker short-circuits).
        migrate_in(&shell_projects, &bs_projects, &bs_user);

        assert_eq!(
            fs::read_to_string(bs_projects.join("ideas/board.json")).unwrap(),
            r#"{"edited":true}"#,
            "idempotent: second run leaves the user's post-migration edit intact"
        );
    }

    #[test]
    fn no_shell_data_still_writes_marker() {
        let home = TempDir::new().unwrap();
        let bs_user = home.path().join(".brainstorm");
        // Shell pool doesn't exist at all.
        migrate_in(
            &home.path().join("DreamStore Projects"),
            &home.path().join("Brainstorm Projects"),
            &bs_user,
        );
        assert!(bs_user.join(MARKER).exists(), "marker written even with nothing to copy");
    }
}
