//! One-time, non-destructive migration of pre-separation Remit data.
//!
//! Before Remit was extracted into this standalone app, the user's transfers
//! and saved recipients lived in the DreamStore shell's dirs
//! (`~/DreamStore Projects/` + `~/.dreamstore/`). Standalone Remit uses its own
//! isolated dirs (`~/Remit Projects/` + `~/.remit/`) and does NOT share that
//! pool. So on first launch we COPY the existing Remit data across once, so the
//! back-catalogue isn't lost. After this one-time copy the two are fully
//! independent — edits on one side never touch the other.
//!
//! Properties:
//!   - **Non-destructive:** the shell's data is only read, never moved/deleted.
//!   - **Remit-only:** only `~/DreamStore Projects/<dir>` folders containing a
//!     `remit.json` are copied; kinetic/pulse/data/brainstorm projects are
//!     skipped.
//!   - **Idempotent:** a marker at `~/.remit/migrated.json` records that the
//!     copy ran, so it never repeats (even if the user later deletes every
//!     copied transfer).
//!   - **Only copies `remit.json`:** the per-project `.claude/` skill symlink +
//!     `CLAUDE.md` are regenerated by `project_open`, so we don't drag stale
//!     copies across.

use std::fs;
use std::path::Path;

const MARKER: &str = "migrated.json";

fn shell_projects_dir() -> Option<std::path::PathBuf> {
    dirs::home_dir().map(|h| h.join("DreamStore Projects"))
}

fn shell_user_dir() -> Option<std::path::PathBuf> {
    dirs::home_dir().map(|h| h.join(".dreamstore"))
}

/// Run the one-time migration against the real dirs. Idempotent; best-effort
/// (a failure to copy any one item is logged to stderr, not fatal — the app
/// still launches).
pub fn migrate_once() {
    let (Some(shell_projects), Some(shell_user)) = (shell_projects_dir(), shell_user_dir()) else {
        return;
    };
    migrate_in(
        &shell_projects,
        &shell_user,
        &crate::paths::projects_dir(),
        &crate::paths::user_dir(),
    );
}

/// Testable core: copy pre-separation Remit data from the shell dirs into the
/// standalone dirs, guarded by a one-shot marker under `remit_user`.
fn migrate_in(shell_projects: &Path, shell_user: &Path, remit_projects: &Path, remit_user: &Path) {
    let marker = remit_user.join(MARKER);
    if marker.exists() {
        return; // already migrated
    }

    let mut copied_projects = 0usize;

    // 1. Copy each shell Remit project (a dir containing remit.json).
    if shell_projects.is_dir() {
        if let Err(e) = fs::create_dir_all(remit_projects) {
            eprintln!("remit migrate: mkdir pool: {}", e);
        }
        if let Ok(entries) = fs::read_dir(shell_projects) {
            for entry in entries.flatten() {
                let src = entry.path();
                if !src.is_dir() || !src.join("remit.json").exists() {
                    continue;
                }
                let Some(name) = src.file_name() else { continue };
                let dst = remit_projects.join(name);
                if dst.exists() {
                    continue; // don't clobber an existing standalone project
                }
                if let Err(e) = fs::create_dir_all(&dst) {
                    eprintln!("remit migrate: mkdir {}: {}", dst.display(), e);
                    continue;
                }
                // Only the doc; the skill bundle + CLAUDE.md are regenerated on open.
                match fs::copy(src.join("remit.json"), dst.join("remit.json")) {
                    Ok(_) => copied_projects += 1,
                    Err(e) => eprintln!("remit migrate: copy {}: {}", src.display(), e),
                }
            }
        }
    }

    // 2. Copy the saved-recipients store if the standalone one doesn't exist yet.
    let src_recipients = shell_user.join("remit-recipients.json");
    let dst_recipients = remit_user.join("remit-recipients.json");
    if src_recipients.exists() && !dst_recipients.exists() {
        if let Err(e) = fs::create_dir_all(remit_user) {
            eprintln!("remit migrate: mkdir user dir: {}", e);
        }
        if let Err(e) = fs::copy(&src_recipients, &dst_recipients) {
            eprintln!("remit migrate: copy recipients: {}", e);
        }
    }

    // 3. Drop the marker so this never runs again.
    if let Err(e) = fs::create_dir_all(remit_user) {
        eprintln!("remit migrate: mkdir user dir for marker: {}", e);
        return;
    }
    let body = format!("{{\"copiedProjects\":{}}}\n", copied_projects);
    if let Err(e) = fs::write(&marker, body) {
        eprintln!("remit migrate: write marker: {}", e);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Build a fake shell Remit project dir with a remit.json.
    fn remit_project(pool: &Path, name: &str, body: &str) {
        let dir = pool.join(name);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("remit.json"), body).unwrap();
    }

    #[test]
    fn copies_remit_projects_and_recipients_once() {
        let home = TempDir::new().unwrap();
        let shell_projects = home.path().join("DreamStore Projects");
        let shell_user = home.path().join(".dreamstore");
        let remit_projects = home.path().join("Remit Projects");
        let remit_user = home.path().join(".remit");

        // Two remit projects + one kinetic project (story.json) that must be skipped.
        remit_project(&shell_projects, "transfer", r#"{"recipient":{"name":"A"}}"#);
        remit_project(&shell_projects, "transfer-2", r#"{"recipient":{"name":"B"}}"#);
        let kinetic = shell_projects.join("v1");
        fs::create_dir_all(&kinetic).unwrap();
        fs::write(kinetic.join("story.json"), "{}").unwrap();
        // A recipients store.
        fs::create_dir_all(&shell_user).unwrap();
        fs::write(shell_user.join("remit-recipients.json"), r#"[{"id":"r1"}]"#).unwrap();

        migrate_in(&shell_projects, &shell_user, &remit_projects, &remit_user);

        // Both remit projects copied (remit.json only), kinetic skipped.
        assert!(remit_projects.join("transfer/remit.json").exists());
        assert!(remit_projects.join("transfer-2/remit.json").exists());
        assert!(!remit_projects.join("v1").exists(), "non-remit project skipped");
        // Recipients copied.
        assert_eq!(
            fs::read_to_string(remit_user.join("remit-recipients.json")).unwrap(),
            r#"[{"id":"r1"}]"#
        );
        // Marker written.
        assert!(remit_user.join(MARKER).exists());
        // Shell data untouched (non-destructive).
        assert!(shell_projects.join("transfer/remit.json").exists());
    }

    #[test]
    fn is_idempotent_and_does_not_reclobber() {
        let home = TempDir::new().unwrap();
        let shell_projects = home.path().join("DreamStore Projects");
        let shell_user = home.path().join(".dreamstore");
        let remit_projects = home.path().join("Remit Projects");
        let remit_user = home.path().join(".remit");
        remit_project(&shell_projects, "transfer", r#"{"recipient":{"name":"A"}}"#);

        migrate_in(&shell_projects, &shell_user, &remit_projects, &remit_user);
        // User edits the copied project after migration.
        fs::write(remit_projects.join("transfer/remit.json"), r#"{"edited":true}"#).unwrap();
        // Second run must NOT overwrite the user's edit (marker short-circuits).
        migrate_in(&shell_projects, &shell_user, &remit_projects, &remit_user);

        assert_eq!(
            fs::read_to_string(remit_projects.join("transfer/remit.json")).unwrap(),
            r#"{"edited":true}"#,
            "idempotent: second run leaves the user's post-migration edit intact"
        );
    }

    #[test]
    fn no_shell_data_still_writes_marker() {
        let home = TempDir::new().unwrap();
        let remit_user = home.path().join(".remit");
        // Shell dirs don't exist at all.
        migrate_in(
            &home.path().join("DreamStore Projects"),
            &home.path().join(".dreamstore"),
            &home.path().join("Remit Projects"),
            &remit_user,
        );
        assert!(remit_user.join(MARKER).exists(), "marker written even with nothing to copy");
    }
}
