/**
 * THE PRODUCT SURFACE — and the parameter editor.
 *
 * A "kinetic story" is a JSON document: a sequence of beats. But this
 * schema does double duty:
 *
 *  1. It's the API/orchestration contract — Claude Code (the orchestrator)
 *     writes story.json matching this shape; Recraft fills in `shape`.
 *
 *  2. It IS the editor. Remotion Studio auto-generates a visual props
 *     editor from this Zod schema: `.min/.max/.step` -> sliders, zColor()
 *     -> color pickers, enums -> dropdowns. So every per-element parameter
 *     you can tweak (easing, scale, direction, dynamics, glow, duration,
 *     order) is just a field here. NO custom editor app needed.
 *
 * Division of control (by design):
 *   - Claude Code owns the SEQUENCE — adding/removing beats, picking
 *     animation kinds, generating shapes. Change the story = reprompt.
 *   - The Studio props editor owns the PARAMETERS — the knobs below.
 *     The user tweaks, never regenerates.
 */
import { z } from "zod";
import { zColor } from "@remotion/zod-types";

// ---------------------------------------------------------------------------
// Shared parameter vocabulary
// ---------------------------------------------------------------------------

/** Easing curve — maps to the eased-progress functions in easings.ts.
 *  This is the "curve" control. */
export const easingSchema = z
  .enum(["power3.out", "power3.inOut", "power4.out", "spring"])
  .describe("Animation curve");

/** Which way an element travels as it animates in. */
export const directionSchema = z
  .enum(["up", "down", "left", "right", "scale"])
  .describe("Entrance direction");

export const beatKindSchema = z
  .enum([
    "reveal", // word builds in, letter by letter
    "morph", // a shape morphs into the word's first letter
    "generativeFill", // the word masks a moving generative noise field
  ])
  .describe("Animation type for this beat");

export type BeatKind = z.infer<typeof beatKindSchema>;
export type Easing = z.infer<typeof easingSchema>;
export type Direction = z.infer<typeof directionSchema>;

// ---------------------------------------------------------------------------
// Beat — one word/phrase + every tweakable parameter for it
// ---------------------------------------------------------------------------

export const beatSchema = z.object({
  // --- content (Claude owns these) ---------------------------------------
  /** the word or short phrase for this beat */
  text: z.string().min(1).describe("Word or phrase"),
  /** which animation drives this beat */
  kind: beatKindSchema.default("reveal"),
  /**
   * For `kind: "morph"` ONLY — the SVG path the first letter morphs FROM.
   * Generated by a vector provider (Recraft) via the `kinetic` CLI. The
   * user does not edit this; to change it, reprompt Claude Code.
   */
  shape: z.string().optional().describe("Morph source path (provider-generated)"),

  // --- timing (tweakable) ------------------------------------------------
  /** how long this beat holds the screen, in seconds (incl. its animation) */
  durationInSeconds: z
    .number()
    .min(0.3)
    .max(10)
    .step(0.1)
    .default(1.5)
    .describe("Beat duration (seconds)"),
  /** fraction of the beat spent animating in vs. holding (0.1–0.9) */
  animateInPortion: z
    .number()
    .min(0.1)
    .max(0.9)
    .step(0.05)
    .default(0.55)
    .describe("Portion of beat spent animating in"),

  // --- motion parameters (tweakable) -------------------------------------
  /** the easing curve for this beat's entrance */
  easing: easingSchema.default("power3.out"),
  /** which way the element comes from */
  direction: directionSchema.default("up"),
  /**
   * "Dynamics" — overall energy of the motion. Scales travel distance,
   * stagger spread and overshoot. 0 = subtle, 1 = punchy.
   */
  dynamics: z
    .number()
    .min(0)
    .max(1)
    .step(0.05)
    .default(0.5)
    .describe("Motion energy (subtle ↔ punchy)"),
  /** per-letter / per-element stagger, in seconds */
  staggerSeconds: z
    .number()
    .min(0)
    .max(0.2)
    .step(0.005)
    .default(0.04)
    .describe("Stagger between elements (seconds)"),
  /** final scale of the element (1 = font size, >1 bigger) */
  scale: z
    .number()
    .min(0.3)
    .max(2.5)
    .step(0.05)
    .default(1)
    .describe("Element scale"),

  // --- look (tweakable) --------------------------------------------------
  /** per-beat text/shape color override (falls back to story palette) */
  color: zColor().optional().describe("Color override"),
  /** glow strength around the element, in px (0 = none) */
  glow: z
    .number()
    .min(0)
    .max(60)
    .step(2)
    .default(0)
    .describe("Glow radius (px)"),
});
export type Beat = z.infer<typeof beatSchema>;

// ---------------------------------------------------------------------------
// Background — the layer behind the type
// ---------------------------------------------------------------------------

/**
 * The story's background. Animated text sits on top of this.
 *  - gradient : an animated mesh gradient (free, code-based)
 *  - shader   : a "shader-like" animated noise/flow field — frame-
 *               deterministic SVG/CSS, NOT WebGL (WebGL can't be made
 *               reliably deterministic per-frame in Remotion). Free.
 *  - image    : a still image file (Remotion <Img>). You supply `src`.
 *  - video    : a video file (Remotion <OffthreadVideo>). You supply `src`.
 *
 * gradient/shader are fully implemented. image/video are stubbed: the
 * schema accepts them and the renderer shows a labelled placeholder until
 * an asset pipeline is wired (the "Claude-generated video" path needs a
 * video-gen API — separate work, separate cost).
 */
export const backgroundKindSchema = z
  .enum(["gradient", "shader", "image", "video"])
  .describe("Background type");

export const backgroundSchema = z.object({
  kind: backgroundKindSchema.default("gradient"),
  /** for image/video: path under public/ or a URL */
  src: z.string().optional().describe("Asset src (image/video only)"),
  /** which shader-style pattern, when kind === "shader" */
  shaderStyle: z
    .enum(["aurora", "flowField", "mesh"])
    .default("aurora")
    .describe("Shader pattern"),
  /** how lively the background animates, 0..1 */
  motion: z
    .number()
    .min(0)
    .max(1)
    .step(0.05)
    .default(0.5)
    .describe("Background motion"),
});
export type Background = z.infer<typeof backgroundSchema>;
export type BackgroundKind = z.infer<typeof backgroundKindSchema>;

// ---------------------------------------------------------------------------
// Story — the whole sequence + the global palette
// ---------------------------------------------------------------------------

export const storySchema = z.object({
  beats: z.array(beatSchema).min(1),

  /** display font size in px (composition authored at 1080x1920) */
  fontSize: z
    .number()
    .min(40)
    .max(400)
    .step(5)
    .default(160)
    .describe("Base font size (px)"),

  // --- palette (tweakable) ----------------------------------------------
  bgColor: zColor().default("#0a0a14").describe("Background color"),
  /** second background color — a subtle gradient is drawn bg→bg2 */
  bgColor2: zColor().default("#1a1030").describe("Background gradient end"),
  textColor: zColor().default("#fafafa").describe("Default text color"),
  accentColor: zColor().default("#7c5cff").describe("Accent color"),
  /** secondary accent — generative fills blend accent→accent2 */
  accent2Color: zColor().default("#ff5ca8").describe("Secondary accent"),

  /** global glow multiplier applied on top of each beat's glow */
  glowIntensity: z
    .number()
    .min(0)
    .max(2)
    .step(0.1)
    .default(1)
    .describe("Global glow multiplier"),

  /** the background layer behind the type */
  background: backgroundSchema.default({
    kind: "gradient",
    shaderStyle: "aurora",
    motion: 0.5,
  }),
});
export type Story = z.infer<typeof storySchema>;

/**
 * Total composition duration, derived from the beats — not hardcoded.
 * Root.tsx feeds this to calculateMetadata so the timeline always matches
 * the script.
 */
export const storyDurationInFrames = (story: Story, fps: number): number => {
  const seconds = story.beats.reduce((s, b) => s + b.durationInSeconds, 0);
  return Math.max(1, Math.round(seconds * fps));
};
